# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apim-analytics-volume-claim-1
  labels:
    app: apim-analytics
    pattern: wso2apim-pattern-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    # This storage size should be change according to the TPS of the server and the record count.
      storage: 20Gi
  selector:
      matchLabels:
        type: local
        pattern: wso2apim-pattern-1
        purpose: apim-analytics-data-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apim-analytics-volume-claim-2
  labels:
    app: apim-analytics
    pattern: wso2apim-pattern-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        # This storage size should be change according to the TPS of the server and the record count.
      storage: 20Gi
  selector:
    matchLabels:
      type: local
      pattern: wso2apim-pattern-1
      purpose: apim-analytics-data-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apim-analytics-conf-volume-claim-1
  labels:
    app: apim-analytics
    pattern: wso2apim-pattern-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
      pattern: wso2apim-pattern-1
      purpose: apim-analytics-conf-analytics-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apim-analytics-conf-volume-claim-2
  labels:
    app: apim-analytics
    pattern: wso2apim-pattern-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
      pattern: wso2apim-pattern-1
      purpose: apim-analytics-conf-analytics-2
