# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2apim-tm
  labels:
    app: wso2apim-tm
    pattern: wso2apim-pattern-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wso2apim-tm
        node: key-manager
    spec:
      containers:
      - image: docker.wso2.com/wso2am-tm-kubernetes:3.0.0
        name: wso2apim-tm
        imagePullPolicy: IfNotPresent
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        env:
          - name: HOST_NAME
            value: "wso2apim-tm"
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: apim-tm-conf
          mountPath: "/home/wso2user/wso2am-3.0.0-conf/conf/"
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 300
          periodSeconds: 20
      serviceAccountName: "wso2svcacct"
      volumes:
      - name: apim-tm-conf
        configMap:
          name: apim-tm-conf